export const SCREENS = {
  HOME: 'SCREEN_HOME',
  //
  TODAY: 'SCREEN_TODAY',
  BOOKINGS: 'SCREEN_BOOKINGS',
  NEWS_FEED: 'SCREEN_NEWS_FEED',
  CONTACTS: 'SCREEN_CONTACTS',
  STAFF: 'SCREEN_STAFF',
  SERVIVES_CATEGORIES: 'SCREEN_SERVIVES_CATEGORIES',
  //
  LOGIN: 'SCREEN_LOGIN',
  //
  ADD_TASK: 'SCREEN_ADD_TASK',
  ADD_APPOINTMENT: 'SCREEN_ADD_APPOINTMENT',
  UPDATE_APPOINTMENT: 'SCREEN_UPDATE_APPOINTMENT',
  CANCEL_APPOINTMENT: 'SCREEN_CANCEL_APPOINTMENT',
  BOOKING_DETAILS: 'SCREEN_BOOKING_DETAILS',
  CLIENT_DETAILS: 'SCREEN_CLIENT_DETAILS',
  SERVIVES: 'SCREEN_SERVIVES',
  INVENTORY: 'SCREEN_INVENTORY',
  TASKS: 'SCREEN_TASKS',
  CHECKOUT: 'SCREEN_CHECKOUT',
  //
  NEW_CLIENT: 'SCREEN_NEW_CLIENT',
  INFO: 'SCREEN_INFO',
  ADDRESS_DETAILS: 'SCREEN_ADDRESS_DETAILS',
  PAYMENT: 'SCREEN_PAYMENT',
  BUSY_TIME: 'SCREEN_BUSY_TIME',

  GOOGLE_WEB: 'SCREEN_GOOGLE_WEB',
};

export const NAVIGATORS = {
  AUTH: 'NAVIGATOR_AUTH',
  APP: 'NAVIGATOR_APP',
  MENU: 'NAVIGATOR_MENU',
  DEFAULT: 'NAVIGATOR_DEFAULT',
};
